include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app.router.dart"
  errors:
    todo: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    ignore_for_file: file_names
    file_names: false
    flutter_style_todos: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
    require_trailing_commas: false
    prefer_const_constructors: true
    noop_primitive_operations: false
    sort_child_properties_last: true
    always_declare_return_types: true
    depend_on_referenced_packages: false
    use_setters_to_change_properties: false
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
