name: arc_apps
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  stacked: ^2.3.13
  stacked_hooks: ^0.2.2
  stacked_services: ^0.9.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  stacked_generator: ^0.7.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
