name: Releases

on:
  push:
    branches: ["master"]

jobs:
  releases:
    name: Release APK
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.0.5"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle
